// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6AD6MRW8RDdPCBGwNCFSEde3ZxQidVmw',
    appId: '1:471012468099:web:af24e756235da9cd4502b6',
    messagingSenderId: '471012468099',
    projectId: 'blog-app-82fd2',
    authDomain: 'blog-app-82fd2.firebaseapp.com',
    storageBucket: 'blog-app-82fd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_x6uvw0Vgjk147lX7qzczh1oO50zWgHU',
    appId: '1:471012468099:android:54fb3a5eb0f38ef04502b6',
    messagingSenderId: '471012468099',
    projectId: 'blog-app-82fd2',
    storageBucket: 'blog-app-82fd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-m-9ldzV9kpnEQGTItZfBZ21oUqe4yNs',
    appId: '1:471012468099:ios:428de96dc02b60844502b6',
    messagingSenderId: '471012468099',
    projectId: 'blog-app-82fd2',
    storageBucket: 'blog-app-82fd2.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );
}
