const supabaseProjectUrl = 'https://vzsqluqtryepxryuxnal.supabase.co';
const supabaseApiKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6c3FsdXF0cnllcHhyeXV4bmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MDM1ODEsImV4cCI6MjA0ODI3OTU4MX0.WwiNagMYSOqz9QEQptwImwR54topEvb2VSEJ9-pCBnY';
